/**
 * Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2025)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React, { memo, ReactElement, useEffect, useRef } from "react"

// eslint-disable-next-line import/no-extraneous-dependencies
import * as vg from "@uwdata/vgplot"

import { MosaicChart as MosaicChartProto } from "@streamlit/protobuf"

export function testConnector() {
  return {
    /**
     * Query the DuckDB server.
     * @param {object} query
     * @param {'exec' | 'arrow' | 'json' | 'create-bundle' | 'load-bundle'} [query.type] The query type.
     * @param {string} [query.sql] A SQL query string.
     * @param {string[]} [query.queries] The queries used to create a bundle.
     * @param {string} [query.name] The name of a bundle to create or load.
     * @returns the query result
     */
    async query(query: any) {
      console.log("query", query)
      return null
    },
  }
}

interface MosaicChartProps {
  element: MosaicChartProto
}

function MosaicChart({ element }: MosaicChartProps): ReactElement {
  const chartContainerRef = useRef<HTMLDivElement>(null)
  console.log("element", element)

  useEffect(() => {
    if (chartContainerRef.current) {
      // configure the coordinator to use DuckDB-WASM
      // creates a new database instance running in-browser
      vg.coordinator().databaseConnector(testConnector())

      // load data into the database
      // executes a query generated by the loadCSV helper
      // vg.coordinator().exec(vg.loadCSV("stocks", "stock-data.csv"))

      // create an area chart, returned as an HTML element
      // you can subsequently add this to your webpage
      const chart = vg.plot(
        vg.areaY(vg.from("stocks"), { x: "Date", y: "Price" })
      )

      // Append the chart to the container
      chartContainerRef.current.appendChild(chart)
    }
  }, [])

  return <div ref={chartContainerRef}></div>
}

export default memo(MosaicChart)
